- descriptor: "pip-services-container:container-info:default:default:1.0"
  name: "pip-services-logging"
  description: "Logging microservice"

- descriptor: "pip-services-commons:logger:console:default:1.0"
  level: "trace"

- descriptor: "pip-services-logging:persistence:memory:default:1.0"

- descriptor: "pip-services-logging:controller:default:default:1.0"

- descriptor: "pip-services-logging:service:http:default:1.0"
  connection:
    protocol: "http"
    host: "0.0.0.0"
    port: 3000
